source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'BrainUp' do
pod 'Alamofire', '~> 4.4'
pod 'PasswordTextField', '~> 1.0.4'
pod 'NVActivityIndicatorView' , '~> 3.6.1'

end
